/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIQuadrato */

#ifndef _Included_JNIQuadrato
#define _Included_JNIQuadrato
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIQuadrato
 * Method:    quadratoSomma
 * Signature: ([I)J
 */
JNIEXPORT jlong JNICALL Java_JNIQuadrato_quadratoSomma
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
